package controle;
import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class Fornecedor extends javax.swing.JInternalFrame {
Conexao con_cliente;
    public Fornecedor() {
        initComponents();
        con_cliente = new Conexao();// inicialização do objeto
        con_cliente.conecta();  // chama o método que conecta
        con_cliente.executaSQL("select * from contato_fornc order by Cod_For");
        preencherTabela();
        posicionarRegistro();
        Tabela.setAutoCreateRowSorter(true);// ativa a classificação ordenada da tabela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cod_For = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        RG = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Comp_Res = new javax.swing.JLabel();
        Cod_Emp = new javax.swing.JLabel();
        cod_for = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        rg = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cod_emp = new javax.swing.JTextField();
        comp_res = new javax.swing.JTextField();
        Primeiro = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Proximo = new javax.swing.JButton();
        Ultimo = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        Gravar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Pesq = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Cod_For.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cod_For.setText("Código Fornecedor:");

        Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nome.setText("Nome:");

        CPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CPF.setText("CPF:");

        RG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RG.setText("RG:");

        Tel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tel.setText("Telefone:");

        Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email.setText("Email:");

        Comp_Res.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Comp_Res.setText("Comprovante de Residência:");

        Cod_Emp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cod_Emp.setText("Código Empresa:");

        cod_for.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_forActionPerformed(evt);
            }
        });

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        cod_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_empActionPerformed(evt);
            }
        });

        comp_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_resActionPerformed(evt);
            }
        });

        Primeiro.setText("Primeiro");
        Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeiroActionPerformed(evt);
            }
        });

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Proximo.setText("Proximo");
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoActionPerformed(evt);
            }
        });

        Ultimo.setText("Ultimo");
        Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoActionPerformed(evt);
            }
        });

        Novo.setText("Novo Registro");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Gravar.setText("Gravar");
        Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Fornecedor", "Nome", "CPF", "RG", "Telefone", "Email", "Comprovante de Residência", "Código Empresa"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        Tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        Pesq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pesq.setText("Pesquisar por nome do funcionário:");

        Pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email)
                                    .addComponent(Tel)
                                    .addComponent(RG)
                                    .addComponent(CPF)
                                    .addComponent(Nome)
                                    .addComponent(Cod_For)
                                    .addComponent(Comp_Res)
                                    .addComponent(Cod_Emp))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cod_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cod_for, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comp_res, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Primeiro)
                                .addGap(18, 18, 18)
                                .addComponent(Anterior)
                                .addGap(18, 18, 18)
                                .addComponent(Proximo)
                                .addGap(18, 18, 18)
                                .addComponent(Ultimo)
                                .addGap(18, 18, 18)
                                .addComponent(Novo)
                                .addGap(18, 18, 18)
                                .addComponent(Gravar)
                                .addGap(18, 18, 18)
                                .addComponent(Alterar)
                                .addGap(18, 18, 18)
                                .addComponent(Excluir)
                                .addGap(18, 18, 18)
                                .addComponent(Voltar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pesq)
                        .addGap(18, 18, 18)
                        .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(558, 558, 558))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cod_For, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_for, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tel)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comp_Res, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comp_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cod_Emp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Primeiro)
                    .addComponent(Anterior)
                    .addComponent(Proximo)
                    .addComponent(Ultimo)
                    .addComponent(Novo)
                    .addComponent(Gravar)
                    .addComponent(Alterar)
                    .addComponent(Excluir)
                    .addComponent(Voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cod_forActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_forActionPerformed

    }//GEN-LAST:event_cod_forActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed

    }//GEN-LAST:event_nomeActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed

    }//GEN-LAST:event_cpfActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed

    }//GEN-LAST:event_rgActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed

    }//GEN-LAST:event_telActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void cod_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_empActionPerformed

    }//GEN-LAST:event_cod_empActionPerformed

    private void comp_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_resActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comp_resActionPerformed

    private void PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeiroActionPerformed
        try{
            con_cliente.resultset.first();
            mostrar_Dados();
        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel posicionar no primeiro registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PrimeiroActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        try{
            con_cliente.resultset.previous();
            mostrar_Dados();
        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel posicionar no registro anterior: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_AnteriorActionPerformed

    private void ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoActionPerformed
        try{
            con_cliente.resultset.next();
            mostrar_Dados();
        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel posicionar no proximo registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ProximoActionPerformed

    private void UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoActionPerformed
        try{
            con_cliente.resultset.last();
            mostrar_Dados();
        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel posicionar o ultimo registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_UltimoActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        cod_for.setText("");
        nome.setText("");
        cpf.setText("");
        rg.setText("");
        tel.setText("");
        email.setText("");
        comp_res.setText("");
        cod_emp.setText("");
        cod_for.requestFocus();
    }//GEN-LAST:event_NovoActionPerformed

    private void GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarActionPerformed
        String COD_FOR = cod_for.getText();
        String NOME = nome.getText();
        String CPF = cpf.getText();
        String RG = rg.getText();
        String TEL = tel.getText();
        String EMAIL = email.getText();
        String COMP_RES = comp_res.getText();
        String COD_EMP = cod_emp.getText();

        try {
            String insert_sql="insert into contato_fornc (Cod_For, Nome, CPF, RG, Telefone, Email, Comp_Res, Cod_Empresa) values ('" + COD_FOR + "', '" + NOME + "', '" + CPF + "', '" + RG + "', '" + TEL + "', '" + EMAIL + "', '" + COMP_RES + "','" + COD_EMP + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null,"Gravação realizada com sucesso!! ","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);

            con_cliente.executaSQL("select * from contato_fornc order by Cod_For");
            preencherTabela();

        }catch (SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Erro na gravação:\n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_GravarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        String COD_FOR = cod_for.getText();
        String NOME = nome.getText();
        String CPF = cpf.getText();
        String RG = rg.getText();
        String TEL = tel.getText();
        String EMAIL = email.getText();
        String COMP_RES = comp_res.getText();
        String COD_EMP = cod_emp.getText();
        String sql;
        String msg="";

        try{
            if(cod_for.getText().equals("")){
                sql="insert into contato_fornc (Cod_For, Nome, CPF, RG, Telefone, Email, Comp_Res, Cod_Empresa) values ('" + COD_FOR + "', '" + NOME + "', '" + CPF + "', '" + RG + "', '" + TEL + "', '" + EMAIL + "', '" + COMP_RES + "','" + COD_EMP + "')";
                msg="Alteração de Registro";
            }else{
                sql="update contato_fornc set Nome='" + NOME + "',CPF='" + CPF + "', RG='" + RG + "', Telefone='" + TEL + "',  Email='" + EMAIL + "', Comp_Res='" + COMP_RES + "', Cod_Empresa='" + COD_EMP + "' where Cod_For= " + cod_for.getText();
                msg="Alteração de Registro";
            }

            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Gravação realizada com sucesso!! ","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);

            con_cliente.executaSQL("select * from contato_fornc order by Cod_For");
            preencherTabela();

        }catch (SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Erro na gravação:\n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        String sql="";
        try{
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Excluir o registro: ","Confirmar Exclusão", JOptionPane.YES_NO_OPTION,3);
            if (resposta==0){
                sql = "delete from contato_fornc where Cod_For = " + cod_for.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                if(excluir==1){
                    JOptionPane.showMessageDialog(null, "Exclusão relizada com sucesso!! ","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from contato_fornc order by Cod_For");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                }else{
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!! ","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch (SQLException excecao){
            JOptionPane.showMessageDialog(null,"Erro na exclusão: "+excecao,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        int linha_selecionada = Tabela.getSelectedRow();
        cod_for.setText(Tabela.getValueAt(linha_selecionada, 0).toString());
        nome.setText(Tabela.getValueAt(linha_selecionada, 1).toString());
        cpf.setText(Tabela.getValueAt(linha_selecionada, 2).toString());
        rg.setText(Tabela.getValueAt(linha_selecionada, 3).toString());
        tel.setText(Tabela.getValueAt(linha_selecionada, 4).toString());
        email.setText(Tabela.getValueAt(linha_selecionada, 5).toString());
        comp_res.setText(Tabela.getValueAt(linha_selecionada, 6).toString());
        cod_emp.setText(Tabela.getValueAt(linha_selecionada, 7).toString());
    }//GEN-LAST:event_TabelaMouseClicked

    private void TabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaKeyPressed
        int linha_selecionada = Tabela.getSelectedRow();
       cod_for.setText(Tabela.getValueAt(linha_selecionada, 0).toString());
        nome.setText(Tabela.getValueAt(linha_selecionada, 1).toString());
        cpf.setText(Tabela.getValueAt(linha_selecionada, 2).toString());
        rg.setText(Tabela.getValueAt(linha_selecionada, 3).toString());
        tel.setText(Tabela.getValueAt(linha_selecionada, 4).toString());
        email.setText(Tabela.getValueAt(linha_selecionada, 5).toString());
        comp_res.setText(Tabela.getValueAt(linha_selecionada, 6).toString());
        cod_emp.setText(Tabela.getValueAt(linha_selecionada, 7).toString());
    }//GEN-LAST:event_TabelaKeyPressed

    private void PesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesquisarKeyReleased
        try{
            String pesquisa = "select * from contato_fornc where nome like '" + Pesquisar.getText() + "%'";
            con_cliente.executaSQL(pesquisa);

            if(con_cliente.resultset.first()){
                preencherTabela();
            }else{
                JOptionPane.showMessageDialog(null, "\n Não existe dados com este parametro!! ","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Dados digitados não foram localizados:\n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PesquisarKeyReleased
  public void posicionarRegistro(){
         try{
             con_cliente.resultset.first();
             mostrar_Dados();
         }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possivel posicionar no primeiro registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
     }
     public void  mostrar_Dados(){
             try{
                 cod_for.setText(con_cliente.resultset.getString("cod_for"));
                 nome.setText(con_cliente.resultset.getString("nome"));
                 cpf.setText(con_cliente.resultset.getString("cpf"));
                 rg.setText(con_cliente.resultset.getString("rg"));
                 tel.setText(con_cliente.resultset.getString("telefone"));
                 email.setText(con_cliente.resultset.getString("email"));
                 comp_res.setText(con_cliente.resultset.getString("comp_res"));
                 cod_emp.setText(con_cliente.resultset.getString("cod_empresa"));
                 
             }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"Não localizou dados: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    
    
    
    public void preencherTabela(){
        Tabela.getColumnModel().getColumn(0).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(2).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(4).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(5).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(6).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(7).setPreferredWidth(150);
        
        DefaultTableModel modelo =(DefaultTableModel) Tabela.getModel();
        modelo.setNumRows(0);
        
         try{
            con_cliente.resultset.beforeFirst();
            while(con_cliente.resultset.next()){
                modelo.addRow(new Object[]{
                    con_cliente.resultset.getString("cod_for"),
                    con_cliente.resultset.getString("nome"),
                    con_cliente.resultset.getString("cpf"),
                    con_cliente.resultset.getString("rg"), 
                    con_cliente.resultset.getString("telefone"), 
                    con_cliente.resultset.getString("email"),
                    con_cliente.resultset.getString("comp_res"), 
                    con_cliente.resultset.getString("cod_empresa")
                });
            }
        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! :\n "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Anterior;
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Cod_Emp;
    private javax.swing.JLabel Cod_For;
    private javax.swing.JLabel Comp_Res;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Gravar;
    private javax.swing.JLabel Nome;
    private javax.swing.JButton Novo;
    private javax.swing.JLabel Pesq;
    private javax.swing.JTextField Pesquisar;
    private javax.swing.JButton Primeiro;
    private javax.swing.JButton Proximo;
    private javax.swing.JLabel RG;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel Tel;
    private javax.swing.JButton Ultimo;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField cod_emp;
    private javax.swing.JTextField cod_for;
    private javax.swing.JTextField comp_res;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
